"""add scientific achievements and awards tables

Revision ID: 02cdb74a3592
Revises: 12057fb2b543
Create Date: 2025-04-26 16:59:42.176412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02cdb74a3592'
down_revision: Union[str, None] = '12057fb2b543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_internship')
    op.drop_table('user')
    op.drop_table('sqlite_sequence')
    op.create_foreign_key(None, 'personal_profile', 'users', ['user_id'], ['id'])
    op.create_table(
        'scientific_achievements',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('achievement_type', sa.String(length=50)),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('publish_date', sa.Date()),
        sa.Column('description', sa.Text()),
        sa.Column('attachment_path', sa.String(length=200)),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_table(
        'scientific_awards',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('award_name', sa.String(length=200), nullable=False),
        sa.Column('award_level', sa.String(length=50)),
        sa.Column('award_date', sa.Date()),
        sa.Column('awarding_body', sa.String(length=100)),
        sa.Column('description', sa.Text()),
        sa.Column('attachment_path', sa.String(length=200)),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_profile', type_='foreignkey')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('major', sa.VARCHAR(length=100), nullable=True),
    sa.Column('teaching_group', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_dual_teacher', sa.VARCHAR(length=10), nullable=True),
    sa.Column('award_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('talent_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ethnicity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('id_number', sa.VARCHAR(length=18), nullable=True),
    sa.Column('political_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('party_join_date', sa.DATE(), nullable=True),
    sa.Column('party_branch', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hometown', sa.VARCHAR(length=100), nullable=True),
    sa.Column('position', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('education_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('degree', sa.VARCHAR(length=50), nullable=True),
    sa.Column('education_date', sa.DATE(), nullable=True),
    sa.Column('degree_date', sa.DATE(), nullable=True),
    sa.Column('bachelor_school', sa.VARCHAR(length=100), nullable=True),
    sa.Column('master_school', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phd_school', sa.VARCHAR(length=100), nullable=True),
    sa.Column('research_direction', sa.VARCHAR(length=200), nullable=True),
    sa.Column('work_start_date', sa.DATE(), nullable=True),
    sa.Column('career_start_date', sa.DATE(), nullable=True),
    sa.Column('highest_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('highest_title_date', sa.DATE(), nullable=True),
    sa.Column('employee_number', sa.INTEGER(), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('photo_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=50), nullable=True),
    sa.Column('teaching_team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('research_team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('project_group', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teacher_internship',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('college', sa.VARCHAR(length=100), nullable=False),
    sa.Column('major', sa.VARCHAR(length=100), nullable=False),
    sa.Column('major_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('student_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('internship_score', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_excellent', sa.BOOLEAN(), nullable=True),
    sa.Column('internship_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('internship_company', sa.VARCHAR(length=200), nullable=False),
    sa.Column('province', sa.VARCHAR(length=50), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('base_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('external_teacher_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('external_teacher_title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('external_teacher_phone', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scientific_awards')
    op.drop_table('scientific_achievements')
    # ### end Alembic commands ###
