name: Deploy to Aliyun

on:
  push:
    branches:
      - main   # 只在 main 分支推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync code to server
        run: |
          rsync -az --delete \
            --exclude-from=".rsyncignore" \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
      
      - name: Remote deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "bash /srv/deploy/university-admin/deploy.sh"

      - name: Health check
        run: |
          curl -f http://${{ secrets.SSH_HOST }}/health
